"NumPy is a numerical computing library. It stores homogeneous data in contiguous memory using ndarrays, making mathematical operations fast. Instead of writing Python loops, it uses vectorization and broadcasting to perform element-wise operations efficiently."

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np 

we use numpy because lists are not made for mathematical operations 
and lists are computationally slower than numpy

we create an array in py using numpy
a list does not behave like a vector. Numpy does so it is only fair to use numpy's when 
we are dealing with numerical data requiring mathematical operations 
we use arrays for its exceptional contiguos same data type memory 
making operations quicker and giving a base for AI ML.

In [6]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a)) #n dimensional array. 0d,1d,2d,3d....
print(a.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


0d - meaning just one number np.array(10) - no other direction 
1d - one direction np.array([1,2,3,4,5])  - one direction
2d two direction other words contain a row and direction - np.array([
                                                                    [1,2,3] ,
                                                                    [4,5,6]
                                                                    ])
3D = 3 dimensions a row, a column, a layer - 2 matrices otherwise 


.ndim , .shape, .size
.ndim  gives dimensions in an array 
.shape gives no of elements present in the array - returns a tuple with (layer, rows, columns)
.size - this just gives total elements in the array

In [31]:
zero_d = np.array(5) 
print(zero_d)
print(zero_d.ndim)
print(zero_d.shape)
print(zero_d.size) 
print("\n")
one_d = np.array([1,2,3,4,5])
print(one_d)
print(one_d.ndim)
print(one_d.shape) 
print(one_d.size) 
print("\n")
two_d = np.array([
    [1,2,3],[1,2,3]    
])
print(two_d)
print(two_d.ndim) 
print(two_d.shape)
print(two_d.size)
print("\n")
three_d = np.array([
    [[1,2], [3,4]],
    [[5,6],[7,8]]
])
print(three_d)
print(three_d.ndim)
print(three_d.shape)
print(three_d.size)


5
0
()
1


[1 2 3 4 5]
1
(5,)
5


[[1 2 3]
 [1 2 3]]
2
(2, 3)
6


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
8


indices - 
[0] - for one indice or a zero d array or a one_d array - normal indexing 
[0][1] - row, column index 
[0][1][2] - first layer, second row, third column
x[1,2,3] 


slicing - 
[start:stop] - n-1 at stop

[:,1] - all rows of column one 
[1,:] - all columns of row one
: this means gimme everything

read it english terms makes it easier to understand.
First row
Last row
First column
Last column
Center element
Top-right element
Bottom-left element
3. Slicing

Print:

2 3
5 6

and

4 5
7 8

using slicing only.


In [30]:
matrix = np.array([
    [1,2,3],[4,5,6],[7,8,9]
])
print(matrix)
print(matrix[0])
print(matrix[2])
print(matrix[: , 0]) #only first column
print(matrix[:,2])
print(matrix[1,1])
print(matrix[0,2])
print(matrix[2,2])


print(matrix[0:2 , 1:3])
print(matrix[1:3 , 0:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[7 8 9]
[1 4 7]
[3 6 9]
5
3
9
[[2 3]
 [5 6]]
[[4 5]
 [7 8]]


vectorization - numpy operations like matrix + 2, matrix **2 etc. or matrix1 + matrix2 


#THE DOUBT WE HAD
broadcasting rules - 
1. A single value (a scalar) can be used with every element of an array.
ex . a = np.array([1,2,3,4,5])
a + 5 
2. Numpy can auto adjust rows and columns and return a complete different array w different dimensions but some cases it wont work
a = np.array([
    [1,2,3],
    [4,5,6]        2x3
])
b = np.array([10,20,30]) 1x3    
answer would be 
a+b
this would work cause shape would be (2,3) and (1,3) 
3.The Actual Broadcasting Rules

Now that you've discovered them yourself, here are the formal rules.

Suppose we compare two shapes.

(2,3)

(2,1)

NumPy starts comparing from the rightmost dimension.

3  vs 1

1 can stretch to 3.

Good.

Next

2 vs 2

Same.

Good.

Broadcasting works.

Another example

(2,3)

(3,)

Compare

3 vs 3

Good.

Next

2 vs (missing)

A missing dimension is treated as 1.

So NumPy thinks

(2,3)

(1,3)

Now

2 vs 1

1 stretches to 2.

Works.

Now

(2,3)

(2,)

Compare

3 vs 2

Neither is 1.

Neither is equal.

❌ Error.

This is exactly the example we discussed earlier.

In [ ]:
marks = np.array([
    [70,80,90],
    [60,75,88]
])

bonus = np.array([5,2,10])

marks + bonus

bonus2 = np.array([[5],[10]])
marks + bonus2


bonus3 = np.array([1,2,3,4]) #this wouldnt work.
marks + bonus3

Boolean Masking 
1. First of imagine we want something filtered out the data, marks > 75 
2. then certain values would be returned matching the condition right? print(marks > 75)
3. nope we get boolean values thats called boolean masking 
4. so to get values you just, print(marks[marks > 75])
 
 for multiple values you just use & | to negate ~
 

In [39]:
marks = np.array([70,80,90,100])
print(marks > 75)

print(marks[marks> 75])

[False  True  True  True]
[ 80  90 100]


now, array manipulation : imagine an array w shape (6,) 
reshape(rows,columns) - (2,3)
The total number of elements must remain the same. (2x3) = 6 done. (4x2) nope!
and a cool trick : use -1 
arr.reshape(2,-1) it automatically fills the rows required or rows that can be filled.
arr.reshape(-1,3)

but it dosent change the array itself permenantly its just that the view is changed.


In [ ]:
elements = np.array([1,2,3,4,5,6,7,8,9])
elements.reshape(3,3)
elements.reshape(-1,3)
elements.reshape(3,-1)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

TRANSPOSE - Remember matrices 
a.T or a.transpose()
simple as that it flips the matrix , makes rows as columns or columns as rows
to return we can also do a.T.T



In [48]:
a = np.array([
    [10,20],
    [30,40],
    [50,60]
])
a.T

array([[10, 30, 50],
       [20, 40, 60]])

Flatten vs Ravel - flatten() returns a copy of the array, while ravel() usually returns a view of the same data. 
Changes to a raveled array often affect the original array, whereas changes to a flattened array do not.
1.a.flatten() will just make an higher dimensional array to one-d
2. flatten() would make you a new array like a copy of the original array
3.ravel() is same as well it just makes the original array into one d

In [52]:
a = np.array([
    [1,2],
    [3,4]
])
b = a.flatten()
b[0] = 100
print(b)

[100   2   3   4]


sum() , max(), min. mean, blah and all
axis = 0 means goes down column wise 
axis = 1 acroos means row wise 
argmin returns the index of smallest , argmax 
standard deviation - tells us how wide the data is spread std()
variance - var()   square of std 


In [ ]:
marks = np.array([
    [80,90,70],
    [60,75,88],
    [95,91,89]
])
print(marks.sum(axis=1))

scores = np.array([72, 81, 95, 67, 88])
students = np.array(["John", "Jane", "Alex", "Sam", "Emma"])
topper_index = np.argmax(scores)
print(students[topper_index])

[240 223 275]


zeros() - makes a zero matrix - np.zeros(2,3)
ones() - makes an singular value matrix - np.ones(2,3)
eye() - makes an identity matrix the number inside representing the 1's in the principal diagonal
identity() - same as eye()
arange() - its just range for numpy's - arrange(0,20,2).reshape(4,-1) start, stop (n-1) , skips
linspace() - its just like arrange linespace(1,10,6) - in six steps go from 1 to 10. no n-1

arange()	                     linspace()
You specify the step size	    You specify the number of values
End value is usually excluded	End value is included


random() - generates random numbers like randint 
.random.randint(1,100(4,3)) - random numbers from 1 to 100 computed to 4 no. of rows and 3 number of columns

In [ ]:
np.random.randint(1,100,(4,3)) 

array([[18, 92, 39],
       [88, 98, 92],
       [39,  9, 87],
       [74, 15, 83]], dtype=int32)

PROJECT USING NUMPY FOR BETTER UNDERSTANDING
1.creating a marks array 
2. creating a names array 
3. creating a subjects array

4. knowing its ndim, shape and size
5. Total marks of the class
Average marks of the class
Highest mark
Lowest mark


In [ ]:
marks = np.array([
    [85, 92, 78, 88, 95],
    [76, 81, 90, 87, 84],
    [91, 89, 94, 85, 90],
    [65, 70, 72, 68, 75],
    [88, 90, 86, 91, 89],
    [95, 94, 97, 96, 98],
    [72, 75, 70, 74, 73],
    [84, 86, 88, 90, 85]
])
students = np.array([
    "John",
    "Emma",
    "Alex",
    "Sophia",
    "Michael",
    "Olivia",
    "David",
    "Sarah"
])
subjects = np.array([
    "Math",
    "Physics",
    "Chemistry",
    "English",
    "Computer Science"
])

In [63]:
print("marks : ")
print(marks.ndim)
print(marks.shape)
print(marks.size)
print("students")
print(students.ndim)
print(students.shape) 
print(students.size) 
print("subjects:")
print(subjects.ndim) 
print(subjects.shape) 
print(subjects.size)

marks : 
2
(8, 5)
40
students
1
(8,)
8
subjects:
1
(5,)
5


In [70]:
print(marks.sum())
print(marks.mean())
print(marks.max())
print(marks.min())



3376
84.4
98
65


In [ ]:
#if we want subject wise we can use axis = 0 and if we were to calculate student wise whats his average and etc, we would want axis = 1 

In [73]:
print("total marks of the students from each subject : " , marks.sum(axis = 0))
print("average of marks from each subject:" ,marks.mean(axis = 0))
print("maximum marks from each subject scored by a student : " , marks.max(axis = 0))
print("minimum marks from each subject scored by a student :" , marks.min(axis =0))


total marks of the students from each subject :  [656 677 675 679 689]
average of marks from each subject: [82.    84.625 84.375 84.875 86.125]
maximum marks from each subject scored by a student :  [95 94 97 96 98]
minimum marks from each subject scored by a student : [65 70 70 68 73]
